import jsPDF from 'jspdf';
import { Transaction, Customer } from '@/types';
import { format } from 'date-fns';

export const generateTransactionReceipt = (
  transaction: Transaction,
  customer: Customer,
  shopName: string = 'Digital Khatabook'
): void => {
  const pdf = new jsPDF();
  
  // Header
  pdf.setFontSize(20);
  pdf.text(shopName, 20, 30);
  
  pdf.setFontSize(16);
  pdf.text('Transaction Receipt', 20, 50);
  
  // Transaction details
  pdf.setFontSize(12);
  const details = [
    `Receipt ID: ${transaction.id}`,
    `Date: ${format(transaction.createdAt, 'dd/MM/yyyy HH:mm')}`,
    `Customer: ${customer.name}`,
    `Phone: ${customer.phone}`,
    `Type: ${transaction.type.toUpperCase()}`,
    `Amount: ₹${transaction.amount}`,
    `Payment Method: ${transaction.paymentMethod.toUpperCase()}`,
  ];
  
  if (transaction.item) {
    details.push(`Item: ${transaction.item}`);
  }
  
  if (transaction.quantity) {
    details.push(`Quantity: ${transaction.quantity}`);
  }
  
  if (transaction.note) {
    details.push(`Note: ${transaction.note}`);
  }
  
  let yPosition = 70;
  details.forEach((detail) => {
    pdf.text(detail, 20, yPosition);
    yPosition += 10;
  });
  
  // Footer
  pdf.setFontSize(10);
  pdf.text('Generated by Digital Khatabook', 20, yPosition + 20);
  
  // Download the PDF
  pdf.save(`receipt-${transaction.id}.pdf`);
};

export const generateCustomerReport = (
  customer: Customer,
  transactions: Transaction[],
  shopName: string = 'Digital Khatabook'
): void => {
  const pdf = new jsPDF();
  
  // Header
  pdf.setFontSize(20);
  pdf.text(shopName, 20, 30);
  
  pdf.setFontSize(16);
  pdf.text('Customer Report', 20, 50);
  
  // Customer details
  pdf.setFontSize(12);
  pdf.text(`Customer: ${customer.name}`, 20, 70);
  pdf.text(`Phone: ${customer.phone}`, 20, 80);
  pdf.text(`Total Credit: ₹${customer.totalCredit}`, 20, 90);
  pdf.text(`Total Debit: ₹${customer.totalDebit}`, 20, 100);
  pdf.text(`Balance: ₹${customer.balance}`, 20, 110);
  
  // Transactions
  pdf.setFontSize(14);
  pdf.text('Transactions:', 20, 130);
  
  pdf.setFontSize(10);
  let yPosition = 140;
  
  transactions.forEach((transaction, index) => {
    if (yPosition > 270) {
      pdf.addPage();
      yPosition = 20;
    }
    
    const transactionText = `${index + 1}. ${format(transaction.createdAt, 'dd/MM/yyyy')} - ${transaction.type.toUpperCase()} - ₹${transaction.amount} - ${transaction.paymentMethod}`;
    pdf.text(transactionText, 20, yPosition);
    yPosition += 8;
  });
  
  // Download the PDF
  pdf.save(`customer-report-${customer.name}.pdf`);
};